# Generated by Django 6.0.6 on 2026-06-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(verbose_name='Условия приема')),
                ('required_documents', models.TextField(verbose_name='Необходимые документы')),
                ('tuition_cost', models.TextField(verbose_name='Стоимость обучения')),
                ('deadlines', models.TextField(verbose_name='Сроки подачи документов')),
                ('committee_contacts', models.TextField(verbose_name='Контакты приемной комиссии')),
            ],
            options={
                'verbose_name': 'Информация для абитуриентов',
                'verbose_name_plural': 'Информация для абитуриентов',
            },
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(verbose_name='История колледжа')),
                ('founded_year', models.IntegerField(verbose_name='Год основания')),
                ('ownership_form', models.CharField(max_length=100, verbose_name='Форма собственности')),
                ('building_info', models.TextField(verbose_name='Информация о здании')),
                ('facilities', models.TextField(verbose_name='Материально-техническая база')),
            ],
            options={
                'verbose_name': 'О колледже',
                'verbose_name_plural': 'О колледже',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('map_embed', models.TextField(blank=True, verbose_name='Код карты (iframe)')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Документ / Лицензия',
                'verbose_name_plural': 'Документы и лицензии',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория галереи',
                'verbose_name_plural': 'Категории галереи',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('code', models.CharField(max_length=50, verbose_name='Код специальности')),
                ('duration', models.CharField(max_length=100, verbose_name='Срок обучения')),
                ('qualification', models.CharField(max_length=255, verbose_name='Квалификация')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание фото')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='main.gallerycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Галерея',
                'ordering': ['-created_at'],
            },
        ),
    ]
