# Generated by Django 6.0.6 on 2026-06-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='map_embed',
        ),
        migrations.AddField(
            model_name='contact',
            name='map_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку из Google Maps, Яндекс.Карт или 2ГИС (кнопка «Поделиться»)', max_length=1000, verbose_name='Ссылка на карту'),
        ),
    ]
