# Generated by Django 6.0.6 on 2026-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_map_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Загрузите PNG или JPG файл логотипа', null=True, upload_to='site/', verbose_name='Логотип колледжа')),
                ('college_name', models.CharField(default='Кочкор-Атинский региональный колледж', max_length=255, verbose_name='Название колледжа')),
                ('subtitle', models.CharField(default='Министерство здравоохранения Кыргызской Республики', max_length=255, verbose_name='Подзаголовок (под названием)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
