# Generated by Django 6.0.6 on 2026-06-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Министерство науки, высшего образования и инноваций Кыргызской Республики', max_length=500, verbose_name='Название министерства')),
                ('title_ru', models.CharField(default='Министерство науки, высшего образования и инноваций Кыргызской Республики', max_length=500, null=True, verbose_name='Название министерства')),
                ('title_ky', models.CharField(default='Министерство науки, высшего образования и инноваций Кыргызской Республики', max_length=500, null=True, verbose_name='Название министерства')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Краткое описание')),
                ('description_ru', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('description_ky', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Краткое описание')),
                ('content', models.TextField(blank=True, verbose_name='Содержание страницы')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('content_ky', models.TextField(blank=True, null=True, verbose_name='Содержание страницы')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ministry/', verbose_name='Логотип / герб министерства')),
                ('website_url', models.URLField(blank=True, help_text='Ссылка будет открываться в новой вкладке', verbose_name='Официальный сайт министерства')),
            ],
            options={
                'verbose_name': 'Страница Министерства',
                'verbose_name_plural': 'Страница Министерства',
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='committee_contacts_ky',
            field=models.TextField(null=True, verbose_name='Контакты приемной комиссии'),
        ),
        migrations.AddField(
            model_name='admission',
            name='committee_contacts_ru',
            field=models.TextField(null=True, verbose_name='Контакты приемной комиссии'),
        ),
        migrations.AddField(
            model_name='admission',
            name='conditions_ky',
            field=models.TextField(null=True, verbose_name='Условия приема'),
        ),
        migrations.AddField(
            model_name='admission',
            name='conditions_ru',
            field=models.TextField(null=True, verbose_name='Условия приема'),
        ),
        migrations.AddField(
            model_name='admission',
            name='deadlines_ky',
            field=models.TextField(null=True, verbose_name='Сроки подачи документов'),
        ),
        migrations.AddField(
            model_name='admission',
            name='deadlines_ru',
            field=models.TextField(null=True, verbose_name='Сроки подачи документов'),
        ),
        migrations.AddField(
            model_name='admission',
            name='required_documents_ky',
            field=models.TextField(null=True, verbose_name='Необходимые документы'),
        ),
        migrations.AddField(
            model_name='admission',
            name='required_documents_ru',
            field=models.TextField(null=True, verbose_name='Необходимые документы'),
        ),
        migrations.AddField(
            model_name='admission',
            name='tuition_cost_ky',
            field=models.TextField(null=True, verbose_name='Стоимость обучения'),
        ),
        migrations.AddField(
            model_name='admission',
            name='tuition_cost_ru',
            field=models.TextField(null=True, verbose_name='Стоимость обучения'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='building_info_ky',
            field=models.TextField(null=True, verbose_name='Информация о здании'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='building_info_ru',
            field=models.TextField(null=True, verbose_name='Информация о здании'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='facilities_ky',
            field=models.TextField(null=True, verbose_name='Материально-техническая база'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='facilities_ru',
            field=models.TextField(null=True, verbose_name='Материально-техническая база'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='history_ky',
            field=models.TextField(null=True, verbose_name='История колледжа'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='history_ru',
            field=models.TextField(null=True, verbose_name='История колледжа'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='ownership_form_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Форма собственности'),
        ),
        migrations.AddField(
            model_name='collegeinfo',
            name='ownership_form_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Форма собственности'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название документа'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание фото'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Описание фото'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ky',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_ky',
            field=models.CharField(default='Кочкор-Атинский региональный колледж', max_length=255, null=True, verbose_name='Название колледжа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='college_name_ru',
            field=models.CharField(default='Кочкор-Атинский региональный колледж', max_length=255, null=True, verbose_name='Название колледжа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission',
            field=models.TextField(blank=True, help_text='Текст миссии — отображается на странице «О колледже»', verbose_name='Миссия колледжа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_ky',
            field=models.TextField(blank=True, help_text='Текст миссии — отображается на странице «О колледже»', null=True, verbose_name='Миссия колледжа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_ru',
            field=models.TextField(blank=True, help_text='Текст миссии — отображается на странице «О колледже»', null=True, verbose_name='Миссия колледжа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subtitle_ky',
            field=models.CharField(default='Министерство науки, высшего образования и инноваций КР', max_length=255, null=True, verbose_name='Подзаголовок (под названием)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subtitle_ru',
            field=models.CharField(default='Министерство науки, высшего образования и инноваций КР', max_length=255, null=True, verbose_name='Подзаголовок (под названием)'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название специальности'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название специальности'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='qualification_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Квалификация'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='qualification_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Квалификация'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='map_url',
            field=models.URLField(blank=True, help_text='Вставьте ссылку на карту (Google Maps, 2ГИС и т.д.) — появится кнопка «Открыть» рядом с картой', max_length=1000, verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='subtitle',
            field=models.CharField(default='Министерство науки, высшего образования и инноваций КР', max_length=255, verbose_name='Подзаголовок (под названием)'),
        ),
    ]
