# Generated by Django 6.0.6 on 2026-06-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ministrypage_admission_committee_contacts_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='PNG или ICO, рекомендуемый размер 32×32 или 64×64 пикселей', null=True, upload_to='site/', verbose_name='Фавикон (иконка вкладки)'),
        ),
    ]
