# Generated by Django 6.0.6 on 2026-06-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeinfo',
            name='photo',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800×600 или шире. Фото отображается в секции «О колледже».', null=True, upload_to='about/', verbose_name='Фото колледжа (секция «О нас»)'),
        ),
    ]
