# Generated by Django 6.0.6 on 2026-06-16 07:42

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_collegeinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeinfo',
            name='photo',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800×600 или шире. Фото отображается в секции «О колледже».', null=True, upload_to='about/', validators=[main.models.validate_file_size], verbose_name='Фото колледжа (секция «О нас»)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, help_text='Разрешены только PDF, DOC, DOCX, максимум 10 МБ.', null=True, upload_to='documents/', validators=[main.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[main.models.validate_file_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ministrypage',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='ministry/', validators=[main.models.validate_file_size], verbose_name='Логотип / герб министерства'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', validators=[main.models.validate_file_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='PNG или ICO, рекомендуемый размер 32×32 или 64×64 пикселей', null=True, upload_to='site/', validators=[main.models.validate_file_size], verbose_name='Фавикон (иконка вкладки)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Загрузите PNG или JPG файл логотипа', null=True, upload_to='site/', validators=[main.models.validate_file_size], verbose_name='Логотип колледжа'),
        ),
    ]
