# Generated by Django 6.0.6 on 2026-06-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_collegeinfo_photo_alter_document_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('question_ky', models.CharField(max_length=500, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_ky', models.TextField(null=True, verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Вопрос (FAQ)',
                'verbose_name_plural': 'Часто задаваемые вопросы (FAQ)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя выпускника')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Имя выпускника')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Имя выпускника')),
                ('role', models.CharField(help_text='Например: Медицинская сестра · Ош', max_length=255, verbose_name='Должность / город')),
                ('role_ru', models.CharField(help_text='Например: Медицинская сестра · Ош', max_length=255, null=True, verbose_name='Должность / город')),
                ('role_ky', models.CharField(help_text='Например: Медицинская сестра · Ош', max_length=255, null=True, verbose_name='Должность / город')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст отзыва')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст отзыва')),
                ('icon', models.CharField(default='fa-user-nurse', help_text='Например: fa-user-nurse, fa-baby, fa-pills, fa-heartbeat', max_length=50, verbose_name='Иконка (Font Awesome класс)')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Рейтинг (1-5)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Отзыв выпускника',
                'verbose_name_plural': 'Отзывы выпускников',
                'ordering': ['order', 'id'],
            },
        ),
    ]
