# Generated by Django 6.0.6 on 2026-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_faq_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='graduates_count',
            field=models.CharField(default='1000+', help_text='Например: 1000+', max_length=50, verbose_name='Количество выпускников'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='teachers_count',
            field=models.CharField(default='30+', help_text='Например: 30+', max_length=50, verbose_name='Количество преподавателей'),
        ),
    ]
