# Generated by Django 6.0.6 on 2026-06-17 10:48

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_sitesettings_graduates_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Фоновое изображение для секции Hero на главной странице', null=True, upload_to='site/', validators=[main.models.validate_file_size], verbose_name='Фон главного баннера'),
        ),
    ]
