# Generated by Django 6.0.6 on 2026-06-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sitesettings_hero_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='classrooms_count',
            field=models.CharField(default='12', help_text='Например: 12', max_length=50, verbose_name='Количество учебных кабинетов'),
        ),
    ]
